apiVersion: v1
kind: Secret
metadata:
  name: cloud-admiral-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  ELASTIC_PASSWORD: {{ .Values.secrets.elasticPassword | b64enc | quote }}